version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ppt_translate_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ppt_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ppt_translate}
      PGDATA: /data/postgres
    volumes:
      - ./db/postgres_data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ppt_translate_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ppt_translate_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./db/pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - ppt_translate_network
    depends_on:
      - postgres

networks:
  ppt_translate_network:
    driver: bridge 