import {
  ArrowRight, 
  Check, 
  ChevronsUpDown, 
  Circle, 
  Copy, 
  Edit, 
  ExternalLink, 
  File, 
  HelpCircle, 
  Home, 
  Loader2, 
  LogOut,
  Mail, 
  MessageSquare, 
  Moon, 
  Plus, 
  PlusCircle, 
  Search, 
  Server, 
  Settings, 
  Share2, 
  Shield, 
  Sun, 
  Trash, 
  Upload,
  User, 
  X, 
  Workflow,
  CreditCard,
  Menu,
  Info
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  info: Info,
  light: Sun,
  loader: Loader2,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  messageSquare: MessageSquare,
  payment: CreditCard,
  plus: Plus,
  plusCircle: PlusCircle,
  pricing: CreditCard,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  upload: Upload,
  user: User,
  x: X,
};

export {Icons};