"""add_payment_transaction_table

Revision ID: 1395b9f8adae
Revises: add_admin_translation_tracking
Create Date: 2025-08-09 07:17:39.043717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1395b9f8adae'
down_revision = 'add_admin_translation_tracking'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=255), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', 'cancelled', name='payment_status'), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transaction_order_number'), ['order_number'], unique=True)

    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_constraint('referral_referral_code_key', type_='unique')
        batch_op.drop_index('ix_referral_referral_code')
        batch_op.create_index(batch_op.f('ix_referral_referral_code'), ['referral_code'], unique=True)

    with op.batch_alter_table('translation_record', schema=None) as batch_op:
        batch_op.drop_index('ix_translation_record_completed_at')
        batch_op.drop_index('ix_translation_record_started_at')
        batch_op.drop_index('ix_translation_record_status')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_referral_code', type_='unique')
        batch_op.drop_index('ix_user_referral_code')
        batch_op.create_index(batch_op.f('ix_user_referral_code'), ['referral_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_referral_code'))
        batch_op.create_index('ix_user_referral_code', ['referral_code'], unique=False)
        batch_op.create_unique_constraint('uq_user_referral_code', ['referral_code'])

    with op.batch_alter_table('translation_record', schema=None) as batch_op:
        batch_op.create_index('ix_translation_record_status', ['status'], unique=False)
        batch_op.create_index('ix_translation_record_started_at', ['started_at'], unique=False)
        batch_op.create_index('ix_translation_record_completed_at', ['completed_at'], unique=False)

    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_referral_code'))
        batch_op.create_index('ix_referral_referral_code', ['referral_code'], unique=False)
        batch_op.create_unique_constraint('referral_referral_code_key', ['referral_code'])

    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transaction_order_number'))

    op.drop_table('payment_transaction')
    # ### end Alembic commands ###
