"""Add GuestTranslation model

Revision ID: 1e0b8b1725d6
Revises: 
Create Date: 2025-05-07 14:11:21.009045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e0b8b1725d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_translation_record', schema=None) as batch_op:
        batch_op.drop_index('ix_guest_translation_record_ip_address')

    op.drop_table('guest_translation_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_translation_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('target_language', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='guest_translation_record_pkey')
    )
    with op.batch_alter_table('guest_translation_record', schema=None) as batch_op:
        batch_op.create_index('ix_guest_translation_record_ip_address', ['ip_address'], unique=False)

    # ### end Alembic commands ###
