"""Initial schema

Revision ID: 47660d7929b4
Revises: 
Create Date: 2025-06-01 21:52:03.829454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47660d7929b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source_language', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_translation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_translation_ip_address'), ['ip_address'], unique=False)

    op.create_table('invitation_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('invitation_code_id', sa.Integer(), nullable=True),
    sa.Column('membership_start', sa.DateTime(), nullable=True),
    sa.Column('membership_end', sa.DateTime(), nullable=True),
    sa.Column('is_paid_user', sa.Boolean(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('monthly_characters_used', sa.Integer(), nullable=True),
    sa.Column('last_character_reset', sa.DateTime(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('google_access_token', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['invitation_code_id'], ['invitation_code.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('translation_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('source_language', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translation_record')
    op.drop_table('user')
    op.drop_table('invitation_code')
    with op.batch_alter_table('guest_translation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_translation_ip_address'))

    op.drop_table('guest_translation')
    # ### end Alembic commands ###
