"""Add referral system tables and user fields

Revision ID: a1b2c3d4e5f6
Revises: 5ea6ec185e5e
Create Date: 2025-06-29 09:01:10.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '5ea6ec185e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create referral table
    op.create_table('referral',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('referrer_user_id', sa.Integer(), nullable=False),
        sa.Column('referee_email', sa.String(length=120), nullable=False),
        sa.Column('referee_user_id', sa.Integer(), nullable=True),
        sa.Column('referral_code', sa.String(length=20), nullable=False),
        sa.Column('status', sa.Enum('pending', 'completed', 'expired', name='referral_status'), nullable=False),
        sa.Column('reward_claimed', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['referee_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['referrer_user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_referral_code'), ['referral_code'], unique=False)

    # Create feedback table
    op.create_table('feedback',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('feedback_text', sa.Text(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column('user_email', sa.String(length=120), nullable=True),
        sa.Column('page_context', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Add referral fields to user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referred_by_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bonus_membership_days', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_referral_code'), ['referral_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_referred_by_code'), ['referred_by_code'], unique=False)
        batch_op.create_unique_constraint('uq_user_referral_code', ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove referral fields from user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_referral_code', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_referred_by_code'))
        batch_op.drop_index(batch_op.f('ix_user_referral_code'))
        batch_op.drop_column('bonus_membership_days')
        batch_op.drop_column('referred_by_code')
        batch_op.drop_column('referral_code')

    # Drop feedback table
    op.drop_table('feedback')
    
    # Drop referral table
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_referral_code'))
    op.drop_table('referral')

    # ### end Alembic commands ### 