"""Make referee_email nullable for Option B referral system

Revision ID: update_referral_nullable_email
Revises: a1b2c3d4e5f6
Create Date: 2025-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'update_referral_nullable_email'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Make referee_email nullable in referral table for Option B (Generic Shareable Links)
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.alter_column('referee_email',
                              existing_type=sa.String(length=120),
                              nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Revert referee_email to not nullable
    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.alter_column('referee_email',
                              existing_type=sa.String(length=120),
                              nullable=False)

    # ### end Alembic commands ### 